// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySql.EntityFrameworkCore.Extensions;
using SmartChoice.Data;

#nullable disable

namespace SmartChoice.Data.Migrations
{
    [DbContext(typeof(SmartChoiceDbContext))]
    partial class SmartChoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            RelationalModelBuilderExtensions.UseCollation(modelBuilder, "utf8mb4_0900_ai_ci");

            MySQLModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("SmartChoice.Domain.Entities.GuestToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<long?>("InviteId")
                        .HasColumnType("bigint")
                        .HasColumnName("invite_id");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_tokens_token_hash");

                    b.HasIndex("InviteId", "CreatedAt")
                        .HasDatabaseName("ix_guest_tokens_invite_created_at");

                    b.HasIndex("IsRevoked", "ExpiresAt")
                        .HasDatabaseName("ix_guest_tokens_revoked_expires_at");

                    b.ToTable("guest_tokens", (string)null);
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Invite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int")
                        .HasColumnName("max_uses");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_invites_code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("ix_invites_active_expires_at");

                    b.ToTable("invites", null, t =>
                        {
                            t.HasCheckConstraint("ck_invites_max_uses", "`max_uses` > 0");

                            t.HasCheckConstraint("ck_invites_used_count", "`used_count` >= 0 AND `used_count` <= `max_uses`");
                        });
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Poll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)")
                        .HasColumnName("question");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId", "CreatedAt")
                        .HasDatabaseName("ix_polls_author_created_at");

                    b.HasIndex("EndsAt", "Status")
                        .HasDatabaseName("ix_polls_ends_at_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_polls_status_created_at");

                    b.ToTable("polls", null, t =>
                        {
                            t.HasCheckConstraint("ck_polls_dates", "`ends_at` IS NULL OR `starts_at` IS NULL OR `ends_at` > `starts_at`");
                        });
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.PollPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("display_order");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("photo_url");

                    b.Property<long>("PollId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_id");

                    b.HasKey("Id");

                    b.HasIndex("PollId")
                        .HasDatabaseName("ix_poll_photos_poll_id");

                    b.HasIndex("PollId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_poll_photos_poll_order");

                    b.ToTable("poll_photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_poll_photos_display_order", "`display_order` >= 1 AND `display_order` <= 4");
                        });
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("details");

                    b.Property<long>("PollId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("reason_code");

                    b.Property<long?>("ReporterGuestTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("reporter_guest_token_id");

                    b.Property<long?>("ReporterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reporter_user_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReporterGuestTokenId")
                        .HasDatabaseName("ix_reports_reporter_guest_token_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_reports_reporter_user_id");

                    b.HasIndex("PollId", "CreatedAt")
                        .HasDatabaseName("ix_reports_poll_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reports_status_created_at");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_actor", "((`reporter_user_id` IS NOT NULL AND `reporter_guest_token_id` IS NULL) OR (`reporter_user_id` IS NULL AND `reporter_guest_token_id` IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.HasIndex("IsActive", "CreatedAt")
                        .HasDatabaseName("ix_users_is_active_created_at");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("GuestTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("guest_token_id");

                    b.Property<long>("PollId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_id");

                    b.Property<long>("PollPhotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_photo_id");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("voted_at");

                    b.Property<long?>("VoterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("voter_user_id");

                    b.HasKey("Id");

                    b.HasIndex("GuestTokenId");

                    b.HasIndex("PollPhotoId");

                    b.HasIndex("VoterUserId");

                    b.HasIndex("PollId", "GuestTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_votes_poll_guest_token");

                    b.HasIndex("PollId", "PollPhotoId")
                        .HasDatabaseName("ix_votes_poll_photo");

                    b.HasIndex("PollId", "VotedAt")
                        .HasDatabaseName("ix_votes_poll_voted_at");

                    b.HasIndex("PollId", "VoterUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_votes_poll_user");

                    b.ToTable("votes", null, t =>
                        {
                            t.HasCheckConstraint("ck_votes_actor", "((`voter_user_id` IS NOT NULL AND `guest_token_id` IS NULL) OR (`voter_user_id` IS NULL AND `guest_token_id` IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.GuestToken", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.Invite", "Invite")
                        .WithMany("GuestTokens")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Invite", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.User", "CreatedByUser")
                        .WithMany("InvitesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Poll", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.User", "AuthorUser")
                        .WithMany("PollsAuthored")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.PollPhoto", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.Poll", "Poll")
                        .WithMany("Photos")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Report", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.Poll", "Poll")
                        .WithMany("Reports")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartChoice.Domain.Entities.GuestToken", "ReporterGuestToken")
                        .WithMany("ReportsFiled")
                        .HasForeignKey("ReporterGuestTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartChoice.Domain.Entities.User", "ReporterUser")
                        .WithMany("ReportsFiled")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Poll");

                    b.Navigation("ReporterGuestToken");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Vote", b =>
                {
                    b.HasOne("SmartChoice.Domain.Entities.GuestToken", "GuestToken")
                        .WithMany("Votes")
                        .HasForeignKey("GuestTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartChoice.Domain.Entities.Poll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartChoice.Domain.Entities.PollPhoto", "PollPhoto")
                        .WithMany("Votes")
                        .HasForeignKey("PollPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartChoice.Domain.Entities.User", "VoterUser")
                        .WithMany("Votes")
                        .HasForeignKey("VoterUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GuestToken");

                    b.Navigation("Poll");

                    b.Navigation("PollPhoto");

                    b.Navigation("VoterUser");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.GuestToken", b =>
                {
                    b.Navigation("ReportsFiled");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Invite", b =>
                {
                    b.Navigation("GuestTokens");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.Poll", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Reports");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.PollPhoto", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SmartChoice.Domain.Entities.User", b =>
                {
                    b.Navigation("InvitesCreated");

                    b.Navigation("PollsAuthored");

                    b.Navigation("ReportsFiled");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
